/*
 * @FilePath: /mac-ui/src/model/App.js
 * @Author: admin@hamm.cn
 * @Date: 2021-08-09 20:51:06
 * @LastEditTime: 2021-08-19 00:38:03
 * @LastEditors: admin@hamm.cn
 * Written by https://hamm.cn
 * @Description: 
 */

export default {
    allAppList: [
        {
            "key": "demo_colorfull",
            "component": "DemoColorFull",
            "icon": "icon-logo-tux",
            "title": "详情介绍",
            "iconColor": "black",
            "iconBgColor": "white",
            "width": 370,
            "height": 310,
            "titleBgColor": "#ff4500",
            "titleColor": "#fff",
        },
        {
            "key": "system_about",
            "component": "SystemAbout",
            "icon": "icon-question",
            "title": "关于本站",
            "iconColor": "#fff",
            "iconBgColor": "#23282d",
            "width": 400,
            "height": 250,
            "disableResize": true,
            "hideInDesktop": true,
        },
        {
            "key": "system_task",
            "component": "SystemTask",
            "icon": "icon-icon_roundclose_fill",
            "title": "强制退出...",
            "iconColor": "#fff",
            "iconBgColor": "#333",
            "width": 370,
            "height": 350,
            "disableResize": true,
            "hideInDesktop": true,
        },
        {
            "key": "demo_demo",
            "component": "Demo",
            "icon": "icon-MIS_chanpinshezhi",
            "title": "DEMO",
            "iconColor": "#fff",
            "iconBgColor": "#db5048",
            "width": 370,
            "height": 350,
            "keepInDock": true,
        },
        {
            "key": "demo_gitee",
            "icon": "icon-gitee",
            "title": "Gitee仓库",
            "iconColor": "#fff",
            "iconBgColor": "rgb(199,29,35)",
            "keepInDock": true,
            "outLink": true,
            "url": "https://gitee.com/thinkerwing"
        },
        {
            "key": "demo_dock",
            "component": "DemoDock",
            "icon": "icon-MIS_bangongOA",
            "title": "常驻Dock应用",
            "iconColor": "#fff",
            "iconBgColor": "#022732",
            "width": 370,
            "height": 350,
            "keepInDock": true,
        },
        {
            "key": "demo_unresize",
            "component": "DemoUnResize",
            "icon": "icon-smallscreen_fill",
            "title": "固定尺寸应用",
            "iconColor": "#fff",
            "iconBgColor": "#1573fa",
            "width": 370,
            "height": 400,
            "disableResize": true,
        },
        {
            "key": "demo_unclose",
            "component": "DemoUnClose",
            "icon": "icon-wechat-fill",
            "title": "Wechat",
            "iconColor": "#fff",
            "iconBgColor": "#24dc72",
            "width": 370,
            "height": 430,
            "hideWhenClose": true
        },
        {
            "key": "demo_hidedesktop",
            "component": "DemoHideDesktop",
            "icon": "icon-shezhi",
            "title": "不在桌面显示",
            "iconColor": "#333",
            "iconBgColor": "#d4dbef",
            "width": 370,
            "height": 300,
            "hideInDesktop": true,
            "keepInDock": true,
        },
        
        {
            "key": "demo_camera",
            "component": "DemoCamera",
            "icon": "icon-camera1",
            "title": "Photo Booth",
            "iconColor": "#fff",
            "iconBgColor": "#E24637",
            "width": 370,
            "height": 540,
            "disableResize": true,
        },
        {
            "key": "demo_multitask",
            "component": "DemoMultiTask",
            "icon": "icon-app",
            "title": "多任务应用",
            "iconColor": "#fff",
            "iconBgColor": "#333",
            "width": 370,
            "height": 400,
            "multiTask": true,
            "keepInDock": true,
        },
        {
            "key": "demo_zhihu",
            "component": "DemoZhihu",
            "icon": "icon-shejiaotubiao-46",
            "title": "知乎简书掘金",
            "iconColor": "#fff",
            "iconBgColor": "#1573fa",
            "width": 370,
            "height": 300,
            "multiTask": true,
            "keepInDock": true,
        },
        {
            "key": "demo_xiecheng",
            "component": "DemoTravel",
            "icon": "icon-xicheng",
            "title": "Travel",
            "iconColor": "#3983e5",
            "iconBgColor": "white",
            "width": 370,
            "height": 400,
            "multiTask": true,
            "keepInDock": true,
        },
        {
            "key": "demo_wyy",
            "component": "DemoWyy",
            "icon": "icon-wangyiyunyinle",
            "title": "网易云",
            "iconColor": "white",
            "iconBgColor": "red",
            "width": 370,
            "height": 400,
            "multiTask": true,
            "keepInDock": true,
        },
        {
            "key": "demo_csdn",
            "icon": "icon-csdn",
            "title": "个人博客",
            "iconColor": "white",
            "iconBgColor": "#fc5531",
            "keepInDock": true,
            "outLink": true,
            "url": "https://blog.csdn.net/daddykei"
        },
    ]
}